typography_spectrum: 0.21733634686097503
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.689432994928211
  lightness: 0.3493965833913535
  saturation: 0.7950865612365305
  rhythmicContrast: 0.28869488276541233
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7731641626451164
analytics:
  google: null
  facebook: null
  twitter: null
name: jeoffrey
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: ELEVATE • EMPOWER • ENGAGE
description: Blueberries heal the liver
purpose: []
